## YAML Template.
---
server:
    port: 8080
logging:
  level:
    org.springframework.security: DEBUG
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/belajarjwt
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                jdbc:
                    use_get_generated_keys: true
                temp:
                    use_jdbc_metadata_defaults: false